per_listener_settings true
listener 8883 192.168.4.1
allow_anonymous false
password_file /etc/mosquitto/aes-passwd
acl_file /etc/mosquitto/aes-acl

cafile /etc/mosquitto/certs/aes-ca.crt
certfile /etc/mosquitto/certs/aes-gateway.crt
keyfile /etc/mosquitto/certs/aes-gateway.key
tls_version tlsv1.2
require_certificate false

persistence true
persistence_location /var/lib/mosquitto/
autosave_interval 60
max_packet_size 8192
message_size_limit 4096
