"""
AES — Skill Manifest Schema
============================
Owner: Son Nguyen (AI Infra)

A Skill is a Hermes-generated detection rule rewrite.
After every resolved incident, Hermes analyzes what happened,
rewrites the detection logic to catch it better next time,
and produces a Skill that goes through:

  sandbox benchmark → HITL Discord ✅ → inject.py hot-reload

Only detection rules are skills. Response actions (OTA, firewall)
are Solutions 1 and 2 — not part of the learning loop.
"""

from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Optional
import uuid


# ─── STATUS ──────────────────────────────────────────────────────────────────

PENDING_HITL = "PENDING_HITL"   # generated, awaiting sandbox + Discord ✅
APPROVED     = "APPROVED"       # Discord ✅ received
INJECTED     = "INJECTED"       # hot-reloaded into monitor agent
REJECTED     = "REJECTED"       # Discord ❌ or sandbox failed


# ─── BENCHMARK ───────────────────────────────────────────────────────────────

@dataclass
class BenchmarkResult:
    """
    Sandbox benchmark results.
    Populated by skills/sandbox.py before HITL approval.
    """
    detection_rate:      float = 0.0   # % of replayed attacks caught (0.0–1.0)
    false_positive_rate: float = 0.0   # % of normal traffic incorrectly flagged (0.0–1.0)
    latency_ms:          float = 0.0   # avg rule evaluation time in ms
    sample_size:         int   = 0     # total samples replayed (attacks + normals)
    normal_sample_size:  int   = 0     # normal readings available for the FP measurement

    def passed(self, min_detection: float = 0.8, max_fp: float = 0.1) -> bool:
        """
        Returns True if benchmark meets deployment thresholds.
        Defaults: detection >= 80%, false positive <= 10%.
        Requires a non-empty normal corpus — otherwise the FP rate is unmeasured
        (always 0%) and the gate would be meaningless (audit finding C4).
        """
        if self.normal_sample_size <= 0:
            return False
        return self.detection_rate >= min_detection and self.false_positive_rate <= max_fp

    def summary(self) -> str:
        return (
            f"detection={self.detection_rate:.0%} "
            f"fp={self.false_positive_rate:.0%} "
            f"latency={self.latency_ms:.1f}ms "
            f"n={self.sample_size} (normals={self.normal_sample_size})"
        )


# ─── SKILL ───────────────────────────────────────────────────────────────────

@dataclass
class Skill:
    """
    A versioned detection rule rewrite generated by Hermes.

    Lifecycle:
        Hermes.rewrite_detection() → Skill(status=PENDING_HITL)
        sandbox.benchmark()        → skill.benchmark populated
        Discord ✅                 → skill.status = APPROVED
        inject.hot_inject()        → skill.status = INJECTED
    """

    # ── Identity ─────────────────────────────────────────────────────────────
    skill_id:    str = field(default_factory=lambda: f"skill-{uuid.uuid4().hex[:8]}")
    version:     int = 1
    created_at:  str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    # ── Provenance ───────────────────────────────────────────────────────────
    incident_id:      str = ""          # which incident triggered this rewrite
    cve_id:           str = "UNKNOWN"   # linked CVE from Intel Agent
    device_type:      str = ""          # e.g. "ESP32-CAM", "Tapo C200"
    attack_signature: str = ""          # what attack pattern this detects better

    # ── Detection Params ──────────────────────────────────────────────────────
    # A skill is a set of EWMA detection params (NOT executable code), e.g.
    #   {"deviation_threshold": 0.4, "simultaneous_threshold": 2}
    # Consumed live by MonitorAgent via config/active_detection.json. No exec().
    params: dict = field(default_factory=dict)
    diff:   str  = ""    # human-readable summary of the param change

    # ── Benchmark ────────────────────────────────────────────────────────────
    benchmark: BenchmarkResult = field(default_factory=BenchmarkResult)

    # ── Approval ─────────────────────────────────────────────────────────────
    status:      str           = PENDING_HITL
    approved_by: Optional[str] = None   # Discord username who clicked ✅
    approved_at: Optional[str] = None   # ISO timestamp of approval

    def approve(self, approved_by: str) -> None:
        """Mark skill as approved after Discord ✅."""
        self.status      = APPROVED
        self.approved_by = approved_by
        self.approved_at = datetime.now(timezone.utc).isoformat()

    def reject(self) -> None:
        """Mark skill as rejected after Discord ❌ or sandbox failure."""
        self.status = REJECTED

    def mark_injected(self) -> None:
        """Mark skill as live after hot-inject."""
        self.status = INJECTED

    def to_dict(self) -> dict:
        d = asdict(self)
        d["benchmark"] = asdict(self.benchmark)
        return d

    @classmethod
    def from_dict(cls, d: dict) -> "Skill":
        benchmark_data = d.pop("benchmark", {})
        skill = cls(**d)
        skill.benchmark = BenchmarkResult(**benchmark_data)
        return skill
